username: 50
email: 50
password: 6
size_avatar: 50
remembers: "1"
width: 537
height: 195
start_year: 25
end_year: 18
fname: 10
lname: 10
emails: "tranthithanhqt1397@gmail.com"
image_maximum: 400
max_thumb: 220
min_thumb: 50
number_of_page: 5
message_self: "self"
message_other: "other"
number_of_page: 3
number: 86400
member: "Member"
